<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Ticket</h1>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Editar Ticket</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>

        <?= $this->partial('cont/ticket/form'); ?>

        <?php if (count($this->attachments) > 0): ?>
            <p><strong>Arquivos</strong></p>
            <ul>
                <?php foreach ($this->attachments as $attachment): ?>
                    <li><a target="_blank" href="<?= $this->basePath('upload/'). $attachment->file;?>"><?= $attachment->name; ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <!-- /.box-body -->

    </div>
    <!-- /.box -->

</section>
<!-- /.content -->