<?= $this->doctype() ?>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?= $this->headTitle('SISCONT')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('dist/css/skins/_all-skins.min.css'))
        ->prependStylesheet($this->basePath('dist/css/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('css/ionicons.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="/" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>ZF3</b></span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg">SISCONT</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">

                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown user user-menu">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <?= $this->gravatar($this->identity()->email, ['img_size'    => 40,])->setAttributes(['class' => 'user-image'])->getImgTag(); ?>
                            <span class="hidden-xs"><?= $this->identity()->name; ?></span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- User image -->
                            <li class="user-header">
                                <?= $this->gravatar($this->identity()->email, ['img_size'    => 80,])->setAttributes(['class' => 'img-circle'])->getImgTag(); ?>

                                <p>
                                    <?= $this->identity()->name; ?>
                                </p>
                            </li>

                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-right">
                                    <a href="<?= $this->url('auth.logout'); ?>" class="btn btn-default btn-flat">Sign out</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <!-- =============================================== -->

    <!-- Left side column. contains the sidebar -->
    <aside class="main-sidebar">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- sidebar menu: : style can be found in sidebar.less -->
            <ul class="sidebar-menu" data-widget="tree">
                <li class="header">MAIN NAVIGATION</li>

                <li>
                    <a href="<?= $this->url('dashboard'); ?>">
                        <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    </a>
                </li>

                <li>
                    <a href="<?= $this->url('ticket', ['controller' => 'Ticket', 'action' => 'plus']); ?>">
                        <i class="fa fa-plus"></i> <span>Novo Ticket</span>
                    </a>
                </li>

                <li>
                    <a href="<?= $this->url('cont.dash'); ?>">
                        <i class="fa fa-dashboard"></i> <span>Contas</span>
                    </a>
                </li>

                <li>
                    <a href="<?= $this->url('cont.lanc'); ?>">
                        <i class="fa fa-plus"></i> <span>Nova conta</span>
                    </a>
                </li>

                <li>
                    <a href="<?= $this->url('cont.rel'); ?>">
                        <i class="fa fa-dashboard"></i> <span>Relacao</span>
                    </a>
                </li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- =============================================== -->

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <?= $this->content ?>
    </div>
    <!-- /.content-wrapper -->

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 2.4.0
        </div>
        <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
        reserved.
    </footer>
</div>
<!-- ./wrapper -->

<!-- Scripts -->
<?= $this->headScript()
    ->prependFile($this->basePath('dist/js/adminlte.min.js'))
    ->prependFile($this->basePath('js/fastclick/lib/fastclick.js'))
    ->prependFile($this->basePath('js/jquery-slimscroll/jquery.slimscroll.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
?>

<?= $this->inlineScript() ?>
</body>
</html>