<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Delete</h1>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Deletar Ticket</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>

        <h2><?= $this->escapeHtml($this->movimentacao->valor); ?></h2>

        <h2 class="text-danger">Atenção</h2>
        <p>Ao deletar este ticket <strong>todos os arquivos e interações relacionados</strong> serão perdidos.</p>
        <p >Tem serteza que deseja deletar este ticket? </p>


        <?php echo $this->form()->openTag($this->form);?>
        <?php echo $this->formHidden($this->form->get('csrf'));?>
        <div class="box-footer">
            <button type="submit" class="btn btn-danger"><i class="fa fa-trash-o"></i> Deletar Ticket</button>
        </div>
        <?php echo $this->form()->closeTag();?>
        <!-- /.box-body -->

    </div>
    <!-- /.box -->

</section>
<!-- /.content -->