<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Ticket</h1>
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Editar Ticket</h3>

            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                    <i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                    <i class="fa fa-times"></i></button>
            </div>
        </div>

        <?php
        echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
        echo $this->flashMessenger()->render('success', ['alert alert-success alert-dismissible']);
        ?>

        <?php echo $this->form()->openTag($this->form); ?>
        <div class="box-body">
            <div class="form-group<?php echo $this->formElementErrors($this->form->get('valor')) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('valor')); ?>
                <?php echo $this->formText($this->form->get('valor')); ?>
                <?php echo $this->formElementErrors($this->form->get('valor')); ?>
            </div>

            <div class="form-group<?php echo $this->formElementErrors($this->form->get('status')) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('status')); ?>
                <?php echo $this->formSelect($this->form->get('status')); ?>
                <?php echo $this->formElementErrors($this->form->get('status')); ?>
            </div>

            <div class="form-group<?php echo $this->formElementErrors($this->form->get('grupo')) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('grupo')); ?>
                <?php echo $this->formSelect($this->form->get('grupo')); ?>
                <?php echo $this->formElementErrors($this->form->get('grupo')); ?>
            </div>

            <div class="form-group<?php echo $this->formElementErrors($this->form->get('data')) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('data')); ?>
                <?php echo $this->formDate($this->form->get('data')); ?>
                <?php echo $this->formElementErrors($this->form->get('data')); ?>
            </div>

            <div class="form-group<?php echo $this->formElementErrors($this->form->get('descricao')) ? ' has-error' : ''; ?>">
                <?php echo $this->formLabel($this->form->get('descricao')); ?>
                <?php echo $this->formText($this->form->get('descricao')); ?>
                <?php echo $this->formElementErrors($this->form->get('descricao')); ?>
            </div>

            <?php echo $this->formHidden($this->form->get('csrf'));  ?>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-floppy-o"></i> Salvar Ticket</button>
            </div>
        </div>
        <?php echo $this->form()->closeTag(); ?>

        <?php if (count($this->attachments) > 0): ?>
            <p><strong>Arquivos</strong></p>
            <ul>
                <?php foreach ($this->attachments as $attachment): ?>
                    <li><a target="_blank" href="<?= $this->basePath('upload/'). $attachment->file;?>"><?= $attachment->name; ?></a></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>

        <!-- /.box-body -->

    </div>
    <!-- /.box -->

</section>
<!-- /.content -->