<div class="login-logo">
    <p><b>ZF3</b> na prática</p>
</div>
<!-- /.login-logo -->
<div class="login-box-body">
    <p class="login-box-msg">Esqueceu sua senha? Crie uma nova.</p>

    <?php
    echo $this->flashMessenger()->render('error', ['alert alert-danger alert-dismissible']);
    echo $this->flashMessenger()->render('success', ['alert alert-success alert-dismissible']);
    ?>

    <?php echo $this->form()->openTag($this->form); ?>
    <div class="form-group<?php echo $this->formElementErrors($this->form->get('password')) ? ' has-error' : ''; ?> has-feedback">
        <?php echo $this->formPassword($this->form->get('password')); ?>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        <?php echo $this->formElementErrors($this->form->get('password')); ?>
    </div>
    <div class="form-group<?php echo $this->formElementErrors($this->form->get('verifypassword')) ? ' has-error' : ''; ?> has-feedback">
        <?php echo $this->formPassword($this->form->get('verifypassword')); ?>
        <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
        <?php echo $this->formElementErrors($this->form->get('verifypassword')); ?>
    </div>
    <?php echo $this->formHidden($this->form->get('csrf'));  ?>
    <div class="row">
        <div class="pull-right col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">Nova senha</button>
        </div>
    </div>
    <?php echo $this->form()->closeTag(); ?>



    <a href="<?= $this->url('auth.login'); ?>">Voltar para login</a><br>

</div>